"""empty message

Revision ID: 00a1a4335aab
Revises: 29275195d82e
Create Date: 2025-05-08 10:02:57.754018

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "00a1a4335aab"
down_revision: Union[str, None] = "29275195d82e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("states_state", sa.Column("latest_version", sa.UUID(), nullable=True))
    op.create_unique_constraint(None, "states_state", ["id"])
    op.create_foreign_key(
        None, "states_state", "states_state_version", ["latest_version"], ["id"]
    )
    op.create_unique_constraint(None, "states_state_version", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("states_state", "latest_version")
    # ### end Alembic commands ###
