"""empty message

Revision ID: 0591bf8a44e4
Revises: 00a1a4335aab
Create Date: 2025-05-08 13:29:27.394997

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0591bf8a44e4"
down_revision: Union[str, None] = "00a1a4335aab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("states_state_hash_key", "states_state", type_="unique")
    op.drop_column("states_state", "hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "states_state",
        sa.Column("hash", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint("states_state_hash_key", "states_state", ["hash"])
    # ### end Alembic commands ###
