"""empty message

Revision ID: 46182cee9368
Revises: 2a59f2010b40
Create Date: 2025-05-09 08:56:45.222044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46182cee9368'
down_revision: Union[str, None] = '2a59f2010b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('states_state', 'created_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("'2025-05-09 08:54:20.753893'::timestamp without time zone"))
    op.alter_column('states_state', 'modified_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("'2025-05-09 08:54:20.753893'::timestamp without time zone"))
    op.alter_column('states_state_version', 'created_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("'2025-05-09 08:54:20.753893'::timestamp without time zone"))
    op.alter_column('states_state_version', 'modified_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("'2025-05-09 08:54:20.753893'::timestamp without time zone"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('states_state_version', 'modified_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("'2025-05-09 08:54:20.753893'::timestamp without time zone"))
    op.alter_column('states_state_version', 'created_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("'2025-05-09 08:54:20.753893'::timestamp without time zone"))
    op.alter_column('states_state', 'modified_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("'2025-05-09 08:54:20.753893'::timestamp without time zone"))
    op.alter_column('states_state', 'created_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("'2025-05-09 08:54:20.753893'::timestamp without time zone"))
    # ### end Alembic commands ###
