"""empty message

Revision ID: 53f87db86ad3
Revises: 46fb357dbeab
Create Date: 2025-05-08 08:37:25.247084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f87db86ad3'
down_revision: Union[str, None] = '46fb357dbeab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states_state',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=256), nullable=False),
    sa.Column('latest_version', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['latest_version'], ['states_state_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_states_state_latest_version'), 'states_state', ['latest_version'], unique=False)
    op.create_table('states_state_version',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('state_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=256), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states_state.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('state_id', 'version', name='states_state_version_unique_state_version_index')
    )
    op.create_index(op.f('ix_states_state_version_state_id'), 'states_state_version', ['state_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_states_state_version_state_id'), table_name='states_state_version')
    op.drop_table('states_state_version')
    op.drop_index(op.f('ix_states_state_latest_version'), table_name='states_state')
    op.drop_table('states_state')
    # ### end Alembic commands ###
