"""empty message

Revision ID: e0dce4f7f320
Revises: e063a1c75b52
Create Date: 2025-05-09 09:05:25.991403

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e0dce4f7f320"
down_revision: Union[str, None] = "e063a1c75b52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "states_state",
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "states_state",
        sa.Column(
            "modified_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "states_state_version",
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "states_state_version",
        sa.Column(
            "modified_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_constraint(
        "states_state_version_unique_state_version_index",
        "states_state_version",
        type_="unique",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "states_state_version_unique_state_version_index",
        "states_state_version",
        ["state_id", "version"],
    )
    op.drop_column("states_state_version", "modified_date")
    op.drop_column("states_state_version", "created_date")
    op.drop_column("states_state", "modified_date")
    op.drop_column("states_state", "created_date")
    # ### end Alembic commands ###
